name: Daily Sync

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC
  workflow_dispatch: # can be run manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "BOT_TOKEN=${{ vars.BOT_TOKEN }}" >> .env
          echo "CHAT_ID=${{ vars.CHAT_ID }}" >> .env

      - name: Build the project
        run: npm run build

      - name: Run sync script
        run: node lib/index.js
